services:
  fullstackapp:
    build:
      context: ./node-app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    env_file:
      - ./dbenv.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 15
volumes:
  mysql-data:
    driver: local
